name: Test RuleScript Optimizer Rules

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Test RuleScript rules
        run: |
          bazel test //pkg/sql/opt/norm:norm_test \
            --test_output=errors \
            --test_timeout=1800 \
            --test_filter=TestRuleScript